import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Home from "../components/Home";

export default function HomePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home/>

      <main className={styles.main}>

      </main>
    </div>
  )
}
